#!/usr/bin/env bash

echo "
-------------------------------------------------------------------------------
Asset NFT Deployment Script
-------------------------------------------------------------------------------
This script deploys an instance of a Asset NFT

Prerequisites:
* This script uses the Seth Ethereum CLI which can be installed from http://dapp.tools by running 'curl https://dapp.tools/install | sh'
* If you want to use an existing deployment of the asset registry, it can be found here: https://github.com/centrifuge/go-centrifuge/blob/develop/build/configs/default_config.yaml

Please specify the following env variables:
* ASSET_MANAGER
* IDENTITY_FACTORY
"
set -ex

ASSET_MANAGER=${ASSET_MANAGER:-0xa0764952f9599cd0c4b3fddcac20293eee99c3e5}
IDENTITY_FACTORY=${IDENTITY_FACTORY:-0x1362EcBf8679243E24fA0EC425d2e10A08223c7D}

dapp update
dapp build --extract
REGISTRY=$(seth send --create out/AssetNFT.bin 'AssetNFT(address, address)' $ASSET_MANAGER $IDENTITY_FACTORY)

set +ex
echo "-------------------------------------------------------------------------------"
echo "Asset NFT registry deployed to: $REGISTRY"
echo "-------------------------------------------------------------------------------"
